version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        versions: ["*"]

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        versions: ["*"]

exclude:
  - "core/models"
  - "core/build"
  - "node_modules"
  - "venv"
