import sys, time
sys.path.insert(0, r"D:\S.A.T.U.R.D.A.Y\SATURDAY_SYSTEM")
from saturday import screen_operator as so
op = so.ScreenOperator()
before = op.screenshot(r"D:\proof_before.png")
print("BEFORE:", before.get("width"), "x", before.get("height"), flush=True)
r1 = op.open_app("notepad", confirm=True)
print("OPEN:", r1, flush=True)
f = op.focus_window("Notepad")
print("FOCUS:", f, flush=True)
time.sleep(0.5)
r2 = op.type_text("hello", confirm=True, window="Notepad")
print("TYPE:", r2, flush=True)
after = op.screenshot(r"D:\proof_after.png")
print("AFTER shot:", after.get("path"), flush=True)
v = op.pixel_change(before["path"], after["path"])
print("VERIFY changed_ratio:", round(v.get("changed_ratio", -1), 4), flush=True)
rd = op.read_screen(after["path"])
print("OCR sees 'hello':", "hello" in rd.get("text", "").lower(), "| text tail:", repr(rd.get("text", "")[-120:]), flush=True)
print("AUDIT lines:", len(open(so.AUDIT_LOG).readlines()) if __import__('os').path.exists(so.AUDIT_LOG) else 0, flush=True)
print("DONE - Notepad left open showing hello", flush=True)
