import os
import json
import time
import logging
import threading
from datetime import datetime

logger = logging.getLogger("SATURDAY.Brain.Obsidian")

DEFAULT_VAULT = os.path.join(os.path.expanduser("~"), "Documents", "SATURDAY-Vault")


class ObsidianBrainLogger:
    def __init__(self, event_bus=None, vault_path=None):
        self.event_bus = event_bus
        self.vault_path = vault_path or os.getenv("SATURDAY_OBSIDIAN_VAULT", DEFAULT_VAULT)
        self.conversation_log = []
        self.thinking_log = []
        self.logic_chains = []
        self._max_buffer = 500
        self._flush_interval = 30
        self._running = False
        self._thread = None

        self._setup_vault()
        self._subscribe_events()

        logger.info(f"ObsidianBrainLogger initialized, vault={self.vault_path}")

    def _setup_vault(self):
        dirs = [
            self.vault_path,
            os.path.join(self.vault_path, "Conversations"),
            os.path.join(self.vault_path, "Thinking"),
            os.path.join(self.vault_path, "Logic"),
            os.path.join(self.vault_path, "System"),
            os.path.join(self.vault_path, "Daily"),
            os.path.join(self.vault_path, "Templates"),
        ]
        for d in dirs:
            os.makedirs(d, exist_ok=True)

        index_file = os.path.join(self.vault_path, "SATURDAY Brain.md")
        if not os.path.exists(index_file):
            with open(index_file, "w", encoding="utf-8") as f:
                f.write(self._index_content())

        daily_file = self._daily_path()
        if not os.path.exists(daily_file):
            with open(daily_file, "w", encoding="utf-8") as f:
                f.write(self._daily_header())

        logger.info("Obsidian vault prepared at %s", self.vault_path)

    def _index_content(self):
        return """---
tags: [saturday, brain, index]
created: %s
---

# SATURDAY Brain

This is SATURDAY AI OS's brain log, organized for Obsidian.

## Navigation

- [[Conversations/]] - All conversation history with user
- [[Thinking/]] - SATURDAY's internal reasoning and thought chains
- [[Logic/]] - Decision logic and chain-of-thought traces
- [[System/]] - System events, alerts, and status changes
- [[Daily/]] - Daily digests and summaries

## Quick Links

- [[SATURDAY Brain MOC]] - Map of Content
- [[Daily/%s]] - Today's log

---

*Auto-generated by SATURDAY AI OS*
""" % (datetime.now().strftime("%Y-%m-%d"), datetime.now().strftime("%Y-%m-%d"))

    def _daily_header(self):
        now = datetime.now()
        return """---
tags: [daily, %s]
date: %s
---

# Daily Log - %s

## Summary

## Conversations

## Thinking

## System Events

""" % (now.strftime("%Y-%m-%d"), now.isoformat(), now.strftime("%B %d, %Y"))

    def _daily_path(self):
        return os.path.join(self.vault_path, "Daily", datetime.now().strftime("%Y-%m-%d") + ".md")

    def _subscribe_events(self):
        if not self.event_bus:
            return
        self.event_bus.subscribe("voice_command", self._on_voice_command)
        self.event_bus.subscribe("voice_response", self._on_voice_response)
        self.event_bus.subscribe("system_alert", self._on_system_alert)
        self.event_bus.subscribe("security_alert", self._on_security_alert)
        self.event_bus.subscribe("admin_mood_update", self._on_mood_update)
        self.event_bus.subscribe("task_completed", self._on_task_completed)
        self.event_bus.subscribe("task_started", self._on_task_started)
        self.event_bus.subscribe("text_command", self._on_text_command)

    def _on_voice_command(self, data):
        text = data.get("command", str(data)) if isinstance(data, dict) else str(data)
        self.log_conversation("user_voice", text)

    def _on_voice_response(self, data):
        text = str(data) if not isinstance(data, dict) else data.get("text", str(data))
        self.log_conversation("saturday_voice", text)

    def _on_text_command(self, data):
        text = data.get("text", str(data)) if isinstance(data, dict) else str(data)
        self.log_conversation("user_text", text)

    def _on_system_alert(self, data):
        msg = data.get("message", str(data)) if isinstance(data, dict) else str(data)
        self.log_system_event("alert", msg, data)

    def _on_security_alert(self, data):
        msg = data.get("type", "unknown") if isinstance(data, dict) else str(data)
        self.log_system_event("security", f"Security alert: {msg}", data)

    def _on_mood_update(self, data):
        if isinstance(data, dict):
            mood = data.get("mood", "unknown")
            score = data.get("score", 0)
            self.log_system_event("mood", f"Admin mood changed to {mood} (score: {score})", data)

    def _on_task_started(self, data):
        if isinstance(data, dict):
            name = data.get("name", "unknown")
            task_id = data.get("task_id", "")
            self.log_thinking(f"Task started: {name} [{task_id}]", data)

    def _on_task_completed(self, data):
        if isinstance(data, dict):
            name = data.get("name", "unknown")
            task_id = data.get("task_id", "")
            result = data.get("result", {})
            self.log_thinking(f"Task completed: {name} [{task_id}]", {"result": result})

    def log_conversation(self, role, text, metadata=None):
        entry = {
            "timestamp": time.time(),
            "iso_time": datetime.now().isoformat(),
            "role": role,
            "text": text,
            "metadata": metadata or {},
        }
        self.conversation_log.append(entry)
        if len(self.conversation_log) > self._max_buffer:
            self.conversation_log = self.conversation_log[-self._max_buffer:]

        self._append_to_daily(f"### {'User' if 'user' in role else 'SATURDAY'} ({role})\n\n{text}\n\n---\n")

        conv_file = os.path.join(self.vault_path, "Conversations", f"conversation-{datetime.now().strftime('%Y-%m-%d')}.md")
        self._append_to_file(conv_file, self._format_conversation_entry(entry))

        logger.debug("Conversation logged: %s: %s", role, text[:80])

    def log_thinking(self, thought, context=None):
        entry = {
            "timestamp": time.time(),
            "iso_time": datetime.now().isoformat(),
            "thought": thought,
            "context": context or {},
        }
        self.thinking_log.append(entry)
        if len(self.thinking_log) > self._max_buffer:
            self.thinking_log = self.thinking_log[-self._max_buffer:]

        thinking_file = os.path.join(self.vault_path, "Thinking", f"thinking-{datetime.now().strftime('%Y-%m-%d')}.md")
        self._append_to_file(thinking_file, self._format_thinking_entry(entry))
        self._append_to_daily(f"### Thinking\n\n{thought}\n")

    def log_logic_chain(self, premise, steps, conclusion, confidence=0.0):
        chain = {
            "timestamp": time.time(),
            "iso_time": datetime.now().isoformat(),
            "premise": premise,
            "steps": steps,
            "conclusion": conclusion,
            "confidence": confidence,
        }
        self.logic_chains.append(chain)
        if len(self.logic_chains) > self._max_buffer:
            self.logic_chains = self.logic_chains[-self._max_buffer:]

        logic_file = os.path.join(self.vault_path, "Logic", f"logic-{datetime.now().strftime('%Y-%m-%d')}.md")
        self._append_to_file(logic_file, self._format_logic_entry(chain))
        self._append_to_daily(f"### Logic Chain\n\n**Premise:** {premise}\n**Conclusion:** {conclusion} (confidence: {confidence:.1%})\n")

    def log_system_event(self, event_type, message, data=None):
        entry = {
            "timestamp": time.time(),
            "iso_time": datetime.now().isoformat(),
            "type": event_type,
            "message": message,
            "data": data or {},
        }
        system_file = os.path.join(self.vault_path, "System", f"system-{datetime.now().strftime('%Y-%m-%d')}.md")
        self._append_to_file(system_file, f"## [{entry['iso_time']}] {event_type.upper()}\n\n{message}\n\n---\n")
        self._append_to_daily(f"### System ({event_type})\n\n{message}\n")

    def _format_conversation_entry(self, entry):
        role_label = "User" if "user" in entry["role"] else "SATURDAY"
        return f"## [{entry['iso_time']}] {role_label} ({entry['role']})\n\n{entry['text']}\n\n---\n"

    def _format_thinking_entry(self, entry):
        return f"## [{entry['iso_time']}] Thought\n\n{entry['thought']}\n\n---\n"

    def _format_logic_entry(self, chain):
        steps_md = "\n".join(f"  {i+1}. {s}" for i, s in enumerate(chain["steps"]))
        return f"""## [{chain['iso_time']}] Logic Chain

**Premise:** {chain['premise']}

**Steps:**
{steps_md}

**Conclusion:** {chain['conclusion']}
**Confidence:** {chain['confidence']:.1%}

---

"""

    def _append_to_file(self, filepath, content):
        try:
            with open(filepath, "a", encoding="utf-8") as f:
                f.write(content)
        except Exception as e:
            logger.warning("Failed to write to %s: %s", filepath, e)

    def _append_to_daily(self, content):
        daily_file = self._daily_path()
        if not os.path.exists(daily_file):
            with open(daily_file, "w", encoding="utf-8") as f:
                f.write(self._daily_header())
        self._append_to_file(daily_file, content)

    def get_recent_conversations(self, limit=20):
        return self.conversation_log[-limit:]

    def get_recent_thinking(self, limit=20):
        return self.thinking_log[-limit:]

    def get_recent_logic(self, limit=10):
        return self.logic_chains[-limit:]

    def get_brain_stats(self):
        return {
            "vault_path": self.vault_path,
            "total_conversations": len(self.conversation_log),
            "total_thoughts": len(self.thinking_log),
            "total_logic_chains": len(self.logic_chains),
            "vault_exists": os.path.exists(self.vault_path),
        }
